"use client";
// AI Learning Path — enter learning metrics, get a personalized study path
// (backend classifies + generates; rule-based when no LLM key is set).
import { useEffect, useState } from "react";
import { apiGet, apiPost } from "../../../lib/api";

const METRICS = [
  { key: "reading_time_minutes", label: "Reading time (min)", min: 0, max: 120 },
  { key: "quiz_score", label: "Quiz score", min: 0, max: 100 },
  { key: "retry_count", label: "Retries", min: 0, max: 10 },
  { key: "comprehension_score", label: "Comprehension", min: 0, max: 100 },
];

export default function AiLearningPathPage() {
  const [chapters, setChapters] = useState([]);
  const [chapterId, setChapterId] = useState("");
  const [metrics, setMetrics] = useState({ reading_time_minutes: 28, quiz_score: 76, retry_count: 1, comprehension_score: 72 });
  const [path, setPath] = useState(null);
  const [status, setStatus] = useState("");

  useEffect(() => {
    apiGet("/chapters").then((c) => { setChapters(c || []); if (c?.length) setChapterId(String(c[0].chapter_id)); }).catch(() => {});
  }, []);

  async function generate() {
    const ch = chapters.find((c) => String(c.chapter_id) === String(chapterId)) || chapters[0];
    if (!ch) { setStatus("No chapters."); return; }
    setStatus("Generating your path…"); setPath(null);
    try {
      const res = await apiPost("/learning-path/generate", {
        chapter_id: ch.chapter_id, chapter_title: ch.chapter_name, ...metrics,
      });
      setPath(res); setStatus("");
    } catch (e) { setStatus("Failed: " + e.message); }
  }

  return (
    <>
      <h1 style={{ fontSize: 26 }}><span className="dev">एआई अध्ययन पथ</span> · AI Learning Path</h1>
      <p style={{ color: "var(--muted)", marginTop: 4 }}>Enter your recent learning signals — we'll classify your reading style and build a path.</p>

      <div className="vb-card" style={{ marginTop: 16 }}>
        <label style={{ fontWeight: 600 }}>Chapter</label>
        <select value={chapterId} onChange={(e) => setChapterId(e.target.value)}
          style={{ display: "block", width: "100%", marginTop: 8, padding: 10, borderRadius: 10, border: "1px solid var(--line)" }}>
          {chapters.map((c) => <option key={c.chapter_id} value={c.chapter_id}>{c.subject_name} · {c.chapter_name}</option>)}
        </select>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px,1fr))", gap: 16, marginTop: 16 }}>
          {METRICS.map((m) => (
            <div key={m.key}>
              <label style={{ fontSize: 13, color: "var(--muted)" }}>{m.label}: <b style={{ color: "var(--ink)" }}>{metrics[m.key]}</b></label>
              <input type="range" min={m.min} max={m.max} value={metrics[m.key]}
                onChange={(e) => setMetrics((s) => ({ ...s, [m.key]: Number(e.target.value) }))}
                style={{ width: "100%", marginTop: 6 }} />
            </div>
          ))}
        </div>

        <button className="vb-btn" style={{ marginTop: 16, background: "var(--saffron)", color: "#fff" }} onClick={generate}>✨ Generate path</button>
        {status && <span style={{ marginLeft: 12, color: "var(--muted)" }}>{status}</span>}
      </div>

      {path && (
        <div className="vb-card" style={{ marginTop: 16 }}>
          <div style={{ display: "flex", justifyContent: "space-between", flexWrap: "wrap", gap: 8 }}>
            <h2 style={{ fontSize: 20 }}>{path.track_title || "Your Path"}</h2>
            <span className="vb-pill">{path.classification}</span>
          </div>
          <p style={{ color: "#6F5B45", marginTop: 8 }}>{path.summary}</p>
          {path.focus_area && <p style={{ marginTop: 8 }}><b>Focus:</b> {path.focus_area}</p>}
          {Array.isArray(path.steps) && (
            <>
              <h3 style={{ marginTop: 14 }}>Steps</h3>
              <ol style={{ marginTop: 6, paddingLeft: 20, lineHeight: 1.9 }}>{path.steps.map((s, i) => <li key={i}>{s}</li>)}</ol>
            </>
          )}
          {Array.isArray(path.recommended_materials) && (
            <>
              <h3 style={{ marginTop: 14 }}>Recommended materials</h3>
              <ul style={{ marginTop: 6, paddingLeft: 20, lineHeight: 1.9 }}>{path.recommended_materials.map((s, i) => <li key={i}>{s}</li>)}</ul>
            </>
          )}
          <div style={{ marginTop: 12, color: "var(--muted)", fontSize: 12 }}>Generated by: {path.provider}{path.note ? ` — ${path.note}` : ""}</div>
        </div>
      )}
    </>
  );
}
