import { useEffect, useState } from "react";
import { View, Text, ScrollView, TouchableOpacity } from "react-native";
import { apiGet, apiPost } from "../api";
import { Screen, Card, Btn, Pill, Muted, C } from "../ui";

const METRICS = [
  { key: "reading_time_minutes", label: "Reading time (min)", step: 2, max: 120 },
  { key: "quiz_score", label: "Quiz score", step: 5, max: 100 },
  { key: "retry_count", label: "Retries", step: 1, max: 10 },
  { key: "comprehension_score", label: "Comprehension", step: 5, max: 100 },
];

export default function AiLearningPathScreen() {
  const [chapters, setChapters] = useState([]);
  const [chId, setChId] = useState(null);
  const [m, setM] = useState({ reading_time_minutes: 28, quiz_score: 76, retry_count: 1, comprehension_score: 72 });
  const [path, setPath] = useState(null);
  const [status, setStatus] = useState("");

  useEffect(() => { apiGet("/chapters").then((c) => { setChapters(c || []); if (c?.length) setChId(c[0].chapter_id); }).catch(() => {}); }, []);

  function bump(k, d, max) { setM((s) => ({ ...s, [k]: Math.max(0, Math.min(max, s[k] + d)) })); }
  async function generate() {
    const ch = chapters.find((c) => c.chapter_id === chId) || chapters[0];
    if (!ch) { setStatus("No chapters."); return; }
    setStatus("Generating…"); setPath(null);
    try { setPath(await apiPost("/learning-path/generate", { chapter_id: ch.chapter_id, chapter_title: ch.chapter_name, ...m })); setStatus(""); }
    catch (e) { setStatus("Failed: " + e.message); }
  }

  return (
    <Screen>
      <Muted style={{ marginBottom: 10 }}>Enter recent learning signals — we'll classify your style and build a path.</Muted>
      <Card>
        <Text style={{ fontWeight: "700", color: C.ink, marginBottom: 8 }}>Chapter</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
          {chapters.map((c) => (
            <TouchableOpacity key={c.chapter_id} onPress={() => setChId(c.chapter_id)}
              style={{ borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7, marginRight: 8, backgroundColor: chId === c.chapter_id ? C.saffron : C.soft }}>
              <Text style={{ color: chId === c.chapter_id ? "#fff" : C.saffronDeep, fontWeight: "700", fontSize: 12 }}>{c.chapter_name}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {METRICS.map((x) => (
          <View key={x.key} style={{ flexDirection: "row", alignItems: "center", marginTop: 14 }}>
            <Text style={{ flex: 1, color: C.ink }}>{x.label}: <Text style={{ fontWeight: "800", color: C.saffronDeep }}>{m[x.key]}</Text></Text>
            <TouchableOpacity onPress={() => bump(x.key, -x.step, x.max)} style={st.step}><Text style={st.stepT}>−</Text></TouchableOpacity>
            <TouchableOpacity onPress={() => bump(x.key, x.step, x.max)} style={st.step}><Text style={st.stepT}>+</Text></TouchableOpacity>
          </View>
        ))}
        <Btn label="✨ Generate path" primary onPress={generate} style={{ marginTop: 16, alignSelf: "flex-start" }} />
        {status ? <Muted style={{ marginTop: 8 }}>{status}</Muted> : null}
      </Card>

      {path && (
        <Card>
          <View style={{ flexDirection: "row", justifyContent: "space-between", flexWrap: "wrap" }}>
            <Text style={{ fontSize: 17, fontWeight: "800", color: C.ink }}>{path.track_title || "Your Path"}</Text>
            <Pill label={path.classification} />
          </View>
          <Text style={{ color: C.copy, marginTop: 8 }}>{path.summary}</Text>
          {path.focus_area ? <Text style={{ marginTop: 8, color: C.ink }}><Text style={{ fontWeight: "700" }}>Focus: </Text>{path.focus_area}</Text> : null}
          {Array.isArray(path.steps) && (
            <View style={{ marginTop: 10 }}>
              <Text style={{ fontWeight: "700", color: C.ink }}>Steps</Text>
              {path.steps.map((s, i) => <Text key={i} style={{ color: C.copy, marginTop: 4 }}>{i + 1}. {s}</Text>)}
            </View>
          )}
          {Array.isArray(path.recommended_materials) && (
            <View style={{ marginTop: 10 }}>
              <Text style={{ fontWeight: "700", color: C.ink }}>Recommended materials</Text>
              {path.recommended_materials.map((s, i) => <Text key={i} style={{ color: C.copy, marginTop: 4 }}>• {s}</Text>)}
            </View>
          )}
          <Muted style={{ marginTop: 10, fontSize: 12 }}>Generated by: {path.provider}</Muted>
        </Card>
      )}
    </Screen>
  );
}

const st = {
  step: { width: 38, height: 38, borderRadius: 10, borderWidth: 1, borderColor: C.line, backgroundColor: "#fff", alignItems: "center", justifyContent: "center", marginLeft: 8 },
  stepT: { fontSize: 20, color: C.saffronDeep, fontWeight: "700" },
};
